#! /bin/bash
# https://www.hackerrank.com/challenges/bash-tutorials---looping-and-skipping/problem
#Your task is to use for loops to display only odd natural numbers from to .
for i in {1..99} ; do 
if (( $i % 2 )); then
echo $i
fi
done