#! /bin/bash
# https://www.hackerrank.com/challenges/bash-tutorials---a-personalized-echo/problem
#Your task is to use for loops to display only odd natural numbers from 

read -r name
echo "Welcome $name"