#! /bin/bash
# https://www.hackerrank.com/challenges/bash-tutorials---looping-and-skipping/problem
# Use a for loop to display the natural numbers from to .
 counter=1
while [ $counter -lt 51 ];
do
   echo $counter      
   counter=$(( $counter + 1 ))
done
